FROM python:3.8

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app/

RUN python -m pip install -U pip && \
    python -m pip install -r requirements.txt

COPY /src/ /app/src/

CMD python src/consumer.py